[build]
  command = "npm run build"  # Replace with your backend build command if needed
  publish = "./backend"     # Adjust to match your backend directory

[dev]
  command = "npm run dev"   # Replace with your front-end development command

[[plugins]]
  package = "@netlify/plugin-nextjs"  # Use the appropriate Astro-related plugin if needed
