[build]
  command = "npm run build"  # Replace with your back-end build command
  publish = "./public"       # Adjust to match your Astro build output directory

[dev]
  command = "npm run dev"    # Replace with your front-end development command
